export const UPDATE_TOKEN_DATA = "UPDATE_TOKEN_DATA";
export const ADD_TOKEN_TO_WATCH = "ADD_TOKEN_TO_WATCH";
export const CACHE_COIN_DATA = "CACHE_COIN_DATA";
export const ADD_EXCHANGE = "ADD_EXCHANGE";
export const SAVE_WEBSOCKET_REF = "SAVE_WEBSOCKET_REF";