export const MS_PER_MINUTE = 60000;
export const FB_API_KEY  = "2646304632067217";
export const CONTENT_LOADING_ERROR = "CONTENT_LOADING_ERROR";
export const CONTENT_LOADING_IN_PROGRESS = "CONTENT_LOADING_IN_PROGRESS";
export const CONTENT_SETTINGS_NOT_COMPLETE = "CONTENT_SETTINGS_NOT_COMPLETE";
